project:
  type: website
  output-dir: docs
  
website:
  title: "Uma Kasichainula"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/uk2465/umamihira
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: broadside
    toc: true

editor: source

